['save_incremental_version', 'Save Incremental &Version']
['save_incremental_backup', 'Save Incremental &Backup']
['tablet_debugger', 'Toggle Tablet Debugger']
['create_template', '&Create Template From Image...']
['create_copy', 'Create Copy &From Current Image']
['open_resources_directory', 'Open Resources Folder']
['rotate_canvas_right', 'Rotate &Canvas Right']
['rotate_canvas_left', 'Rotate Canvas &Left']
['reset_canvas_rotation', 'R&eset Canvas Rotation']
['wrap_around_mode', '&Wrap Around Mode']
['level_of_detail_mode', '&Instant Preview Mode']
['softProof', 'Soft &Proofing']
['gamutCheck', '&Out of Gamut Warnings']
['showStatusBar', 'Show Status &Bar']
['view_show_canvas_only', '&Show Canvas Only']
['edit_blacklist_cleanup', 'Cleanup removed files...']
['ruler_pixel_multiple2', 'Use multiple of 2 for pixel scale']
['view_ruler', 'Show &Rulers']
['rulers_track_mouse', 'Rul&ers Track Pointer']
['zoom_to_100pct', '&Reset zoom']
['view_zoom_in', 'Zoom &In']
['view_zoom_out', 'Zoom &Out']
['settings_active_author', '&Active Author Profile']
['view_pixel_grid', 'Show Pi&xel Grid']
['toggle_fg_bg', 'Swap Foreground and Background Color']
['reset_fg_bg', 'Reset Foreground and Background Color']
['filter_apply_again', '&Apply Filter Again']
['filter_apply_reprompt', 'Apply &Filter Again (Reprompt)']
['adjust_filters', 'A&djust']
['krita_filter_asc-cdl', '&Slope, Offset, Power...']
['krita_filter_autocontrast', '&Auto Contrast']
['blur_filters', '&Blur']
['krita_filter_blur', '&Blur...']
['krita_filter_burn', '&Burn...']
['krita_filter_colorbalance', '&Color Balance...']
['color_filters', '&Colors']
['krita_filter_colortoalpha', '&Color to Alpha...']
['krita_filter_colortransfer', 'Color &Transfer...']
['krita_filter_crosschannel', 'C&ross-channel adjustment curves...']
['krita_filter_desaturate', '&Desaturate...']
['krita_filter_dodge', 'D&odge...']
['edge_filters', '&Edge Detection']
['krita_filter_edge detection', '&Edge Detection...']
['emboss_filters', 'Emboss']
['krita_filter_emboss', '&Emboss with Variable Depth...']
['krita_filter_emboss all directions', 'Emboss &in All Directions']
['krita_filter_emboss horizontal and vertical', 'Emboss &Horizontal && Vertical']
['krita_filter_emboss horizontal only', 'Emboss Horizontal &Only']
['krita_filter_emboss laplascian', 'Emboss (&Laplacian)']
['krita_filter_emboss vertical only', 'Emboss &Vertical Only']
['krita_filter_gaussian blur', '&Gaussian Blur...']
['krita_filter_gaussianhighpass', '&Gaussian High Pass...']
['enhance_filters', 'E&nhance']
['krita_filter_gaussiannoisereducer', '&Gaussian Noise Reduction...']
['map_filters', '&Map']
['krita_filter_gradientmap', '&Gradient Map...']
['artistic_filters', 'Ar&tistic']
['krita_filter_halftone', '&Halftone...']
['krita_filter_height to normal', '&Height to Normal Map...']
['krita_filter_hsvadjustment', '&HSV Adjustment...']
['krita_filter_indexcolors', '&Index Colors...']
['krita_filter_invert', '&Invert']
['krita_filter_lens blur', '&Lens Blur...']
['krita_filter_levels', '&Levels...']
['krita_filter_maximize', 'M&aximize Channel']
['krita_filter_mean removal', '&Mean Removal']
['krita_filter_minimize', 'M&inimize Channel']
['krita_filter_motion blur', '&Motion Blur...']
['other_filters', '&Other']
['krita_filter_noise', '&Random Noise...']
['krita_filter_normalize', '&Normalize']
['krita_filter_oilpaint', '&Oilpaint...']
['krita_filter_palettize', '&Palettize...']
['krita_filter_perchannel', 'Color Ad&justment curves...']
['krita_filter_phongbumpmap', 'Phong &Bumpmap...']
['krita_filter_pixelize', '&Pixelize...']
['krita_filter_posterize', 'Po&sterize...']
['krita_filter_raindrops', '&Raindrops...']
['krita_filter_randompick', 'Random &Pick...']
['krita_filter_roundcorners', '&Round Corners...']
['krita_filter_sharpen', '&Sharpen']
['krita_filter_smalltiles', '&Small Tiles...']
['krita_filter_threshold', '&Threshold...']
['krita_filter_unsharp', '&Unsharp Mask...']
['krita_filter_wave', '&Wave...']
['krita_filter_waveletnoisereducer', '&Wavelet Noise Reducer...']
['edit_cut', 'Cu&t']
['edit_copy', '&Copy']
['edit_paste', '&Paste']
['copy_sharp', 'C&opy (sharp)']
['cut_sharp', 'Cut (&sharp)']
['paste_new', 'Paste into &New Image']
['paste_at', 'Paste &at Cursor']
['paste_as_reference', 'Paste as R&eference Image']
['copy_merged', 'Copy &merged']
['select_all', 'Select &All']
['deselect', '&Deselect']
['clear', 'C&lear']
['reselect', '&Reselect']
['invert_selection', '&Invert Selection']
['copy_selection_to_new_layer', 'Copy &Selection to New Layer']
['cut_selection_to_new_layer', 'Cut Selection &to New Layer']
['fill_selection_foreground_color', '&Fill with Foreground Color']
['fill_selection_background_color', 'Fill &with Background Color']
['fill_selection_pattern', 'F&ill with Pattern']
['fill_selection_foreground_color_opacity', '&Fill with Foreground Color (Opacity)']
['fill_selection_background_color_opacity', 'Fill &with Background Color (Opacity)']
['fill_selection_pattern_opacity', 'Fill with &Pattern (Opacity)']
['stroke_shapes', 'Stro&ke selected shapes']
['toggle_display_selection', 'Dis&play Selection']
['resizeimagetoselection', 'Trim to S&election']
['edit_selection', 'Edit Selection']
['convert_to_vector_selection', '&Convert to Vector Selection']
['convert_to_raster_selection', 'Co&nvert to Raster Selection']
['convert_shapes_to_vector_selection', 'Convert Shapes to &Vector Selection']
['convert_selection_to_shape', 'Convert &to Shape']
['toggle-selection-overlay-mode', '&Toggle Selection Display Mode']
['stroke_selection', 'Stroke Selec&tion...']
['view_show_guides', 'Show Guides']
['view_lock_guides', '&Lock Guides']
['view_snap_to_guides', '&Snap to Guides']
['show_snap_options_popup', 'Show Snap Options Popup']
['view_snap_orthogonal', 'Snap &Orthogonal']
['view_snap_node', 'Snap &Node']
['view_snap_extension', 'Snap &Extension']
['view_snap_intersection', 'Snap &Intersection']
['view_snap_bounding_box', 'Snap &Bounding Box']
['view_snap_image_bounds', 'Sn&ap Image Bounds']
['view_snap_image_center', 'Snap Image &Center']
['view_snap_to_pixel', 'Snap &Pixel']
['flatten_image', 'Flatten ima&ge']
['merge_layer', 'Merge with Layer Below']
['flatten_layer', '&Flatten Layer']
['rasterize_layer', '&Rasterize Layer']
['save_groups_as_images', 'Save &Group Layers...']
['convert_group_to_animated', 'Convert group to &animated layer']
['resizeimagetolayer', 'Trim to Current &Layer']
['trim_to_image', '&Trim to Image Size']
['layer_style', 'La&yer Style...']
['mirrorNodeX', 'Mirror Layer Hori&zontally']
['mirrorNodeY', 'Mirror Layer &Vertically']
['mirrorAllNodesX', 'Mirror All Layers Hori&zontally']
['mirrorAllNodesY', 'Mirror All Layers &Vertically']
['activateNextLayer', 'Activate next layer']
['activateNextSiblingLayer', 'Activate next sibling layer, skipping over groups.']
['activatePreviousLayer', 'Activate previous layer']
['activatePreviousSiblingLayer', 'Activate previous sibling layer, skipping over groups.']
['switchToPreviouslyActiveNode', 'Activate previously selected layer']
['save_node_as_image', '&Save Layer/Mask...']
['save_vector_node_to_svg', 'Save &Vector Layer as SVG...']
['duplicatelayer', '&Duplicate Layer or Mask']
['copy_layer_clipboard', 'C&opy Layer']
['cut_layer_clipboard', 'Cut &Layer']
['paste_layer_from_clipboard', 'Paste Layer']
['create_quick_group', '&Quick Group']
['create_quick_clipping_group', 'Quick &Clipping Group']
['quick_ungroup', 'Quick &Ungroup']
['select_all_layers', '&All Layers']
['select_visible_layers', '&Visible Layers']
['select_locked_layers', '&Locked Layers']
['select_invisible_layers', '&Invisible Layers']
['select_unlocked_layers', '&Unlocked Layers']
['new_from_visible', '&New Layer From Visible']
['show_in_timeline', 'Show in Timeline']
['add_new_paint_layer', '&Paint Layer']
['add_new_group_layer', '&Group Layer']
['add_new_clone_layer', '&Clone Layer']
['add_new_shape_layer', '&Vector Layer']
['add_new_adjustment_layer', '&Filter Layer...']
['add_new_fill_layer', '&Fill Layer...']
['add_new_file_layer', '&File Layer...']
['add_new_transparency_mask', '&Transparency Mask']
['add_new_filter_mask', '&Filter Mask...']
['add_new_colorize_mask', '&Colorize Mask']
['add_new_transform_mask', '&Transform Mask']
['add_new_selection_mask', '&Local Selection']
['convert_to_paint_layer', 'to &Paint Layer']
['convert_to_selection_mask', 'to &Selection Mask']
['convert_to_filter_mask', 'to &Filter Mask...']
['convert_to_transparency_mask', 'to &Transparency Mask']
['convert_to_animated', 'Convert to &animated layer']
['convert_to_file_layer', 'to File &Layer...']
['isolate_active_layer', '&Isolate Active Layer']
['toggle_layer_visibility', 'Toggle layer &visibility']
['toggle_layer_lock', '&Toggle layer lock']
['toggle_layer_inherit_alpha', 'Toggle layer alpha &inheritance']
['toggle_layer_alpha_lock', 'Toggle layer &alpha']
['split_alpha_into_mask', '&Alpha into Mask']
['split_alpha_write', '&Write as Alpha']
['split_alpha_save_merged', '&Save Merged...']
['import_layer_from_file', 'I&mport Layer...']
['image_properties', '&Properties...']
['import_layer_as_paint_layer', '&as Paint Layer...']
['import_layer_as_transparency_mask', 'as &Transparency Mask...']
['import_layer_as_filter_mask', 'as &Filter Mask...']
['import_layer_as_selection_mask', 'as &Selection Mask...']
['image_color', '&Image Background Color and Transparency...']
['view_grid', 'Show &Grid']
['view_snap_to_grid', 'Snap &To Grid']
['view_toggle_painting_assistants', 'S&how Painting Assistants']
['view_toggle_assistant_previews', 'Show &Assistant Previews']
['view_toggle_reference_images', 'Show Re&ference Images']
['make_brush_color_lighter', 'Make brush color lighter']
['make_brush_color_darker', 'Make brush color darker']
['make_brush_color_saturated', 'Make brush color more saturated']
['make_brush_color_desaturated', 'Make brush color more desaturated']
['shift_brush_color_clockwise', 'Shift brush color hue clockwise']
['shift_brush_color_counter_clockwise', 'Shift brush color hue counter-clockwise']
['make_brush_color_redder', 'Make brush color more red']
['make_brush_color_greener', 'Make brush color more green']
['make_brush_color_bluer', 'Make brush color more blue']
['make_brush_color_yellower', 'Make brush color more yellow']
['increase_opacity', 'Increase opacity']
['decrease_opacity', 'Decrease opacity']
['mirror_canvas', '&Mirror View']
['patterns', '&Patterns']
['gradients', '&Gradients']
['dual', '&Color']
['erase_action', 'Set eraser mode']
['reload_preset_action', 'Reload Original Preset']
['preserve_alpha', 'Preserve Alpha']
['mirrorX-hideDecorations', 'Hide Mirror X Line']
['mirrorX-lock', 'Lock X Line']
['mirrorX-moveToCenter', 'Move to Canvas Center X']
['mirrorY-hideDecorations', 'Hide Mirror Y Line']
['mirrorY-lock', 'Lock Y Line']
['mirrorY-moveToCenter', 'Move to Canvas Center Y']
['hmirror_action', 'Horizontal Mirror Tool']
['vmirror_action', 'Vertical Mirror Tool']
['Next Blending Mode', 'Next Blending Mode']
['Previous Blending Mode', 'Previous Blending Mode']
['Select Normal Blending Mode', 'Select Normal Blending Mode']
['Select Dissolve Blending Mode', 'Select Dissolve Blending Mode']
['Select Behind Blending Mode', 'Select Behind Blending Mode']
['Select Clear Blending Mode', 'Select Clear Blending Mode']
['Select Darken Blending Mode', 'Select Darken Blending Mode']
['Select Multiply Blending Mode', 'Select Multiply Blending Mode']
['Select Color Burn Blending Mode', 'Select Color Burn Blending Mode']
['Select Linear Burn Blending Mode', 'Select Linear Burn Blending Mode']
['Select Lighten Blending Mode', 'Select Lighten Blending Mode']
['Select Screen Blending Mode', 'Select Screen Blending Mode']
['Select Color Dodge Blending Mode', 'Select Color Dodge Blending Mode']
['Select Linear Dodge Blending Mode', 'Select Linear Dodge Blending Mode']
['Select Overlay Blending Mode', 'Select Overlay Blending Mode']
['Select Hard Overlay Blending Mode', 'Select Hard Overlay Blending Mode']
['Select Soft Light Blending Mode', 'Select Soft Light Blending Mode']
['Select Hard Light Blending Mode', 'Select Hard Light Blending Mode']
['Select Vivid Light Blending Mode', 'Select Vivid Light Blending Mode']
['Select Linear Light Blending Mode', 'Select Linear Light Blending Mode']
['Select Pin Light Blending Mode', 'Select Pin Light Blending Mode']
['Select Hard Mix Blending Mode', 'Select Hard Mix Blending Mode']
['Select Difference Blending Mode', 'Select Difference Blending Mode']
['Select Exclusion Blending Mode', 'Select Exclusion Blending Mode']
['Select Hue Blending Mode', 'Select Hue Blending Mode']
['Select Saturation Blending Mode', 'Select Saturation Blending Mode']
['Select Color Blending Mode', 'Select Color Blending Mode']
['Select Luminosity Blending Mode', 'Select Luminosity Blending Mode']
['composite_actions', 'Brush composite']
['brushslider1', 'Brush option slider 1']
['brushslider2', 'Brush option slider 2']
['brushslider3', 'Brush option slider 3']
['brushslider4', 'Brush option slider 4']
['next_favorite_preset', 'Next Favourite Preset']
['previous_favorite_preset', 'Previous Favourite Preset']
['previous_preset', 'Switch to Previous Preset']
['show_brush_editor', 'Show Brush Editor']
['show_brush_presets', 'Show Brush Presets']
['mirror_actions', 'Mirror']
['workspaces', 'Workspaces']
['disable_pressure', 'Use Pen Pressure']
['paintops', "&Painter's Tools"]
['buginfo', '&Show Krita log for bug reports.']
['sysinfo', 'Show system &information for bug reports.']
['clones_array', 'Clones &Array...']
['colorrange', 'S&elect from Color Range...']
['selectopaque', 'Select &Opaque (Replace)']
['selectopaque_add', 'Select Opaque (&Add)']
['selectopaque_subtract', 'Select Opaque (&Subtract)']
['selectopaque_intersect', 'Select Opaque (&Intersect)']
['imagecolorspaceconversion', '&Convert Image Color Space...']
['layercolorspaceconversion', '&Convert Layer Color Space...']
['imagesize', 'Scale Image To &New Size...']
['canvassize', 'R&esize Canvas...']
['layersize', 'Scale &Layer to new Size...']
['scaleAllLayers', 'Scale All &Layers to new Size...']
['selectionscale', 'Sca&le...']
['imagesplit', 'Im&age Split ']
['LayerGroupSwitcher/previous', 'Move into previous group']
['LayerGroupSwitcher/next', 'Move into next group']
['layersplit', '&Split Layer...']
['EditLayerMetaData', '&Edit metadata...']
['growselection', '&Grow Selection...']
['shrinkselection', 'S&hrink Selection...']
['borderselection', '&Border Selection...']
['featherselection', '&Feather Selection...']
['smoothselection', 'S&mooth']
['offsetimage', '&Offset Image...']
['offsetlayer', '&Offset Layer...']
['QMic', "&Start G'MIC-Qt"]
['QMicAgain', "&Re-apply the last G'MIC filter"]
['import_bundles', 'Import Bundles...']
['import_brushes', 'Import Brushes...']
['import_gradients', 'Import Gradients...']
['import_palettes', 'Import Palettes...']
['import_patterns', 'Import Patterns...']
['import_presets', 'Import Presets...']
['import_workspaces', 'Import Workspaces...']
['create_bundle', 'Create Resource Bundle...']
['manage_bundles', '&Manage Resources...']
['rotateimage', '&Rotate Image...']
['rotateImageCW90', 'Rotate &Image 90° to the Right']
['rotateImage180', 'Rotate Image &180°']
['rotateImageCCW90', 'Rotate Image &90° to the Left']
['mirrorImageHorizontal', '&Mirror Image Horizontally']
['mirrorImageVertical', 'Mirror Image &Vertically']
['rotatelayer', '&Rotate Layer...']
['rotateLayer180', 'Rotate Layer &180°']
['rotateLayerCW90', 'Rotate &Layer 90° to the Right']
['rotateLayerCCW90', 'Rotate Layer &90° to the Left']
['rotateAllLayers', '&Rotate All Layers...']
['rotateAllLayersCW90', 'Rotate All &Layers 90° to the Right']
['rotateAllLayersCCW90', 'Rotate All Layers &90° to the Left']
['rotateAllLayers180', 'Rotate All Layers &180°']
['separate', 'Separate Ima&ge...']
['shearimage', '&Shear Image...']
['shearlayer', '&Shear Layer...']
['shearAllLayers', '&Shear All Layers...']
['waveletdecompose', '&Wavelet Decompose ...']
['add_blank_frame', 'Create Blank Frame']
['add_duplicate_frame', 'Create Duplicate Frame']
['remove_frames', 'Remove Keyframe']
['insert_opacity_keyframe', 'Add opacity keyframe']
['remove_opacity_keyframe', 'Remove opacity keyframe']
['previous_frame', 'Previous Frame']
['next_frame', 'Next Frame']
['previous_keyframe', 'Previous Key Frame']
['next_keyframe', 'Next Key Frame']
['first_frame', 'First Frame']
['last_frame', 'Last Frame']
['lazy_frame', 'Auto Frame Mode (on)']
['drop_frames', 'Drop Frames (on)']
['toggle_playback', 'Play / Stop']
['show-global-selection-mask', '&Show Global Selection Mask']
['RenameCurrentLayer', 'Rename current layer']
['layer_properties', '&Properties...']
['remove_layer', '&Remove Layer']
['move_layer_up', 'Move Layer or Mask Up']
['move_layer_down', 'Move Layer or Mask Down']
['set-copy-from', 'Set Copy F&rom...']
['toggle_onion_skin', 'Toggle onion skin']
['create_snapshot', 'Create Snapshot']
['switchto_snapshot', 'Switch to Selected Snapshot']
['remove_snapshot', 'Remove Selected Snapshot']
['insert_column_left', 'Insert Column Left']
['insert_column_right', 'Insert Column Right']
['insert_multiple_columns', 'Insert Multiple Columns']
['remove_columns_and_pull', 'Remove Column and Pull']
['remove_columns', 'Remove Column']
['insert_hold_column', 'Insert Hold Column']
['insert_multiple_hold_columns', 'Insert Multiple Hold Columns']
['remove_hold_column', 'Remove Hold Column']
['remove_multiple_hold_columns', 'Remove Multiple Hold Columns']
['mirror_columns', 'Mirror Columns']
['copy_columns_to_clipboard', 'Copy Columns to Clipboard']
['cut_columns_to_clipboard', 'Cut Columns to Clipboard']
['paste_columns_from_clipboard', 'Paste Columns from Clipboard']
['insert_keyframe_left', 'Insert Keyframe Left']
['insert_keyframe_right', 'Insert Keyframe Right']
['insert_multiple_keyframes', 'Insert Multiple Keyframes']
['remove_frames_and_pull', 'Remove Frame and Pull']
['insert_hold_frame', 'Insert Hold Frame']
['insert_multiple_hold_frames', 'Insert Multiple Hold Frames']
['remove_hold_frame', 'Remove Hold Frame']
['remove_multiple_hold_frames', 'Remove Multiple Hold Frames']
['mirror_frames', 'Mirror Frames']
['copy_frames_to_clipboard', 'Copy to Clipboard']
['cut_frames_to_clipboard', 'Cut to Clipboard']
['paste_frames_from_clipboard', 'Paste from Clipboard']
['set_start_time', 'Set Start Time']
['set_end_time', 'Set End Time']
['update_playback_range', 'Update Playback Range']
['increase_brush_size', 'Increase Brush Size']
['decrease_brush_size', 'Decrease Brush Size']
['selection_tool_mode_add', 'Selection Mode: Add']
['selection_tool_mode_replace', 'Selection Mode: Replace']
['selection_tool_mode_subtract', 'Selection Mode: Subtract']
['selection_tool_mode_intersect', 'Selection Mode: Intersect']
['undo_polygon_selection', 'Undo Polygon Selection Points']
['movetool-move-up', 'Move up']
['movetool-move-down', 'Move down']
['movetool-move-left', 'Move left']
['movetool-move-right', 'Move right']
['movetool-move-up-more', 'Move up more']
['movetool-move-down-more', 'Move down more']
['movetool-move-left-more', 'Move left more']
['movetool-move-right-more', 'Move right more']
['movetool-show-coordinates', 'Show Coordinates']
['set_no_brush_smoothing', 'Brush Smoothing: Disabled']
['set_simple_brush_smoothing', 'Brush Smoothing: Basic']
['set_weighted_brush_smoothing', 'Brush Smoothing: Weighted']
['set_stabilizer_brush_smoothing', 'Brush Smoothing: Stabilizer']
['toggle_assistant', 'Toggle Snap To Assistants']
['calligraphy_increase_width', 'Calligraphy: increase width']
['calligraphy_decrease_width', 'Calligraphy: decrease width']
['calligraphy_increase_angle', 'Calligraphy: increase angle']
['calligraphy_decrease_angle', 'Calligraphy: decrease angle']
['object_order_front', 'Bring to &Front']
['object_order_raise', '&Raise']
['object_order_lower', '&Lower']
['object_order_back', 'Send to &Back']
['object_transform_rotate_90_cw', 'Rotate 90° CW']
['object_transform_rotate_90_ccw', 'Rotate 90° CCW']
['object_transform_rotate_180', 'Rotate 180°']
['object_transform_mirror_horizontally', 'Mirror Horizontally']
['object_transform_mirror_vertically', 'Mirror Vertically']
['object_transform_reset', 'Reset Transformations']
['pathpoint-corner', 'Corner point']
['pathpoint-smooth', 'Smooth point']
['pathpoint-symmetric', 'Symmetric Point']
['pathpoint-curve', 'Make curve point']
['pathpoint-line', 'Make line point']
['pathsegment-line', 'Segment to Line']
['pathsegment-curve', 'Segment to Curve']
['pathpoint-insert', 'Insert point']
['pathpoint-remove', 'Remove point']
['path-break-point', 'Break at point']
['path-break-segment', 'Break at segment']
['pathpoint-join', 'Join with segment']
['pathpoint-merge', 'Merge points']
['convert-to-path', 'To Path']
['object_align_horizontal_left', 'Align Left']
['object_align_horizontal_center', 'Horizontally Center']
['object_align_horizontal_right', 'Align Right']
['object_align_vertical_top', 'Align Top']
['object_align_vertical_center', 'Vertically Center']
['object_align_vertical_bottom', 'Align Bottom']
['object_distribute_horizontal_left', 'Distribute Left']
['object_distribute_horizontal_center', 'Distribute Centers Horizontally']
['object_distribute_horizontal_right', 'Distribute Right']
['object_distribute_horizontal_gaps', 'Distribute Horizontal Gap']
['object_distribute_vertical_top', 'Distribute Top']
['object_distribute_vertical_center', 'Distribute Centers Vertically']
['object_distribute_vertical_bottom', 'Distribute Bottom']
['object_distribute_vertical_gaps', 'Distribute Vertical Gap']
['object_group', 'Group']
['object_ungroup', 'Ungroup']
['object_unite', 'Unite']
['object_intersect', 'Intersect']
['object_subtract', 'Subtract']
['object_split', 'Split']
['file_new', '&New...']
['file_open', '&Open...']
['file_quit', '&Quit']
['options_configure_toolbars', 'Configure Tool&bars...']
['fullscreen', 'F&ull Screen Mode']
['file_open_recent', 'Open &Recent']
['file_save', '&Save']
['file_save_as', 'Save &As...']
['edit_undo', 'Undo ']
['edit_redo', 'Redo ']
['file_import_animation', 'I&mport animation frames...']
['render_animation', 'Render Anima&tion...']
['render_animation_again', '&Render Animation Again']
['file_close_all', '&Close All']
['file_import_file', 'Open ex&isting Document as Untitled Document...']
['file_export_file', 'E&xport...']
['file_documentinfo', '&Document Information']
['theme_menu', '&Themes']
['view_toggledockers', '&Show Dockers']
['reset_configurations', '&Reset Krita Configurations']
['view_detached_canvas', '&Detach canvas']
['settings_dockers_menu', '&Dockers']
['window', '&Window']
['windows_cascade', 'C&ascade']
['windows_tile', '&Tile']
['windows_next', 'N&ext']
['windows_previous', '&Previous']
['view_newwindow', '&New Window']
['file_close', 'C&lose']
['file_sessions', 'S&essions...']
['options_configure', '&Configure Krita...']
['expanding_spacer_0', 'Expanding Spacer']
['expanding_spacer_1', 'Expanding Spacer']
['help_contents', 'Krita &Handbook']
['help_report_bug', '&Report Bug...']
['switch_application_language', 'Switch Application &Language...']
['help_about_app', '&About Krita']
['help_about_kde', 'About &KDE']
['c_canvas_rotation', '&Custom Canvas Rotation']
['kanvasbuddy', '&KanvasBuddy']
['kanvasbuddy2', 'K&anvasBuddy2']
['pieMenu', '&Pie Menu']
['pieMenuSettings', 'Pie &Menu Settings']
['color_space', 'C&olor Space']
['document_tools', '&Document Tools']
['export_layers', '&Export Layers']
['filter_manager', '&Filter Manager']
['plugin_importer', '&Import Python Plugin...']
['python_scripter', '&Scripter']
['ten_brushes', '&Ten Brushes']
['activate_preset_1', 'Activate Brush Preset 1']
['activate_preset_2', 'Activate Brush Preset 2']
['activate_preset_3', 'Activate Brush Preset 3']
['activate_preset_4', 'Activate Brush Preset 4']
['activate_preset_5', 'Activate Brush Preset 5']
['activate_preset_6', 'Activate Brush Preset 6']
['activate_preset_7', 'Activate Brush Preset 7']
['activate_preset_8', 'Activate Brush Preset 8']
['activate_preset_9', 'Activate Brush Preset 9']
['activate_preset_0', 'Activate Brush Preset 0']
['ten_scripts', 'Te&n Scripts']
['execute_script_1', 'Execute Script 1']
['execute_script_2', 'Execute Script 2']
['execute_script_3', 'Execute Script 3']
['execute_script_4', 'Execute Script 4']
['execute_script_5', 'Execute Script 5']
['execute_script_6', 'Execute Script 6']
['execute_script_7', 'Execute Script 7']
['execute_script_8', 'Execute Script 8']
['execute_script_9', 'Execute Script 9']
['execute_script_10', 'Execute Script 10']
['BrushesAndStuff', 'Hide Brushes and Stuff Toolbar']
['mainToolBar', 'Hide File Toolbar']
['view_zoom', 'Zoom']
['KritaShape/KisToolMeasure', 'Measurement Tool']
['KisToolSelectPolygonal', 'Polygonal Selection Tool']
['ZoomTool', 'Zoom Tool']
['KritaTransform/KisToolMove', 'Move Tool']
['SvgTextTool', 'Text Tool']
['KisToolPolygon', 'Polygon Tool']
['KisToolPolyline', 'Polyline Tool']
['KisToolCrop', 'Crop Tool']
['KritaShape/KisToolBrush', 'Freehand Brush Tool']
['KisToolSelectPath', 'Bezier Curve Selection Tool']
['KarbonCalligraphyTool', 'Calligraphy']
['KisToolSelectElliptical', 'Elliptical Selection Tool']
['KritaFill/KisToolGradient', 'Draw a gradient.']
['KritaShape/KisToolMultiBrush', 'Multibrush Tool']
['KritaFill/KisToolFill', 'Fill Tool']
['KisToolSelectSimilar', 'Similar Color Selection Tool']
['KritaShape/KisToolLazyBrush', 'Colorize Mask Tool']
['KisToolSelectContiguous', 'Contiguous Selection Tool']
['KisToolSelectRectangular', 'Rectangular Selection Tool']
['KisToolPencil', 'Freehand Path Tool']
['KritaShape/KisToolRectangle', 'Rectangle Tool']
['KritaShape/KisToolLine', 'Line Tool']
['KritaShape/KisToolSmartPatch', 'Smart Patch Tool']
['KisToolSelectMagnetic', 'Magnetic Selection Tool']
['KritaShape/KisToolEllipse', 'Ellipse Tool']
['KritaSelected/KisToolColorPicker', 'Color Picker']
['KisToolPath', 'Bezier Curve Tool']
['KisToolTransform', 'Transform Tool']
['PanTool', 'Pan Tool']
['ToolReferenceImages', 'Reference Images Tool']
['KritaShape/KisToolDyna', 'Dynamic Brush Tool']
['PathTool', 'Edit Shapes Tool']
['KisAssistantTool', 'Assistant Tool']
['InteractionTool', 'Select Shapes Tool']
['KisToolSelectOutline', 'Outline Selection Tool']
['show_color_selector', 'Show color selector']
['show_mypaint_shade_selector', 'Show MyPaint shade selector']
['show_minimal_shade_selector', 'Show minimal shade selector']
['show_color_history', 'Show color history']
['show_common_colors', 'Show common colors']
['update_composition', 'Update Composition']
['rename_composition', 'Rename Composition...']
