<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Pie Menu</text>
        
        <Action name="pieMenu">
        <icon></icon>
        <text>Pie Menu</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>`</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>